export const TOGGLE_SIDENAVBAR = "TOGGLE_SIDENAVBAR";
export const SET_LOGIN_SIGN_UP_STATUS = "SET_LOGIN_SIGN_UP_STATUS";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const AUTHENTICATION_SUCCESS = "LOGIN_SUCCESS";
export const AUTHENTICATION_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_GOALS = "GET_GOALS";
export const CREATE_GOAL = "CREATE_GOAL"
export const UPDATE_GOAL = "UPDATE_GOAL";
export const UPDATE_GOAL_ORDER = "UPDATE_GOAL_ORDER";
export const DELETE_GOAL = "DELETE_GOAL";
export const GOALS_ERROR = "GOALS_ERROR";
export const SHOW_GOAL_EDIT_MODAL = "SHOW_GOAL_EDIT_MODAL";
export const SHOW_MAIN_LIST = "SHOW_MAIN_LIST";
export const CREATE_TASK = "CREATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const TASKS_ERROR = "TASKS_ERROR";
export const CREATE_NOTE = "CREATE_NOTE";
export const GET_NOTES = "GET_NOTES";
export const NOTES_ERROR = "NOTE_ERROR";
export const SET_GOAL_TO_EDIT = "SET_GOAL_TO_EDIT"
export const UPDATE_TASK_ORDER = "UPDATE_TASK_ORDER";

// CALENDAR ACTIONS 
export const DATE_RANGE_CHANGE = "DATE_RANGE_CHANGE";
export const SELECTED_DATE_CHANGE = "SELECTED_DATE_CHANGE";
